# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/arco/arco-wallpaper.jpg'

# Special
background='#12161e'
foreground='#e1e4e9'
cursor='#e1e4e9'

# Colors
color0='#12161e'
color1='#5E81AB'
color2='#7192B6'
color3='#7FA0C0'
color4='#99A6B4'
color5='#80A1C0'
color6='#B2BAC6'
color7='#e1e4e9'
color8='#9d9fa3'
color9='#5E81AB'
color10='#7192B6'
color11='#7FA0C0'
color12='#99A6B4'
color13='#80A1C0'
color14='#B2BAC6'
color15='#e1e4e9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
