#!/bin/bash

CONFIG="$HOME/.config/arco-chadwm/wofi/config"
STYLE="$HOME/.config/arco-chadwm/wofi/style.css"
COLORS="$HOME/.config/arco-chadwm/wofi/colors"

if [[ ! $(pidof rofi) ]]; then
	rofi --show drun --prompt 'Search...' --conf ${CONFIG} --style ${STYLE} --color ${COLORS}
else
	pkill rofi
fi
